src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StageRepository::class)
 */
class Stage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $backgroundColor;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPlaceMax;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endTime;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startTime;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="stage", fetch="EAGER")
     */
    private $reservations;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->backgroundColor;
    }

    public function setBackgroundColor(?string $backgroundColor): self
    {
        $this->backgroundColor = $backgroundColor;

        return $this;
    }

    public function getNbPlaceMax(): ?int
    {
        return $this->nbPlaceMax;
    }

    public function setNbPlaceMax(int $nbPlaceMax): self
    {
        $this->nbPlaceMax = $nbPlaceMax;

        return $this;
    }


    // fonction pour afficher le nombre de place restante dans la session 
    public function getRemainingPlaces(){
        $somme = 0;
        foreach($this->reservations as $reservation)
        {
            $res = $reservation->getNbPlaces();
            $somme += $res;
        }    
        $reserved =  $this->nbPlaceMax - $somme;
            return $reserved;
        }


        // fonction pour afficher le nombre de place réserver pour la session 
        public function getNbPlaceReserved(){
        $somme = 0;
        foreach($this->reservations as $reservation)
        {
            $res= $reservation->getNbPlaces();
            $somme += $res;          
        }
        return $somme;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setStage($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getStage() === $this) {
                $reservation->setStage(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/ManagementController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\User;
use App\Entity\Input;
use App\Entity\Stage;
use App\Form\BlogType;
use App\Entity\Benefit;
use App\Entity\Session;
use App\Form\InputType;
use App\Form\StageType;
use App\Entity\Category;
use App\Form\BenefitType;
use App\Form\CategoryType;
use App\Entity\Reservation;
use App\Repository\InputRepository;
use App\Entity\ImgCollectionBenefit;
use App\Repository\BenefitRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class ManagementController extends AbstractController
{

    /**
     * fonction pour afficher les catégories des différentes préstations
     * @Route("/admin/management", name="app_management")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $categorys = $doctrine->getRepository(Category::class)->findAll();
        return $this->render('management/index.html.twig', [
            'categorys' => $categorys,
        ]);
    }

    
    /**
     * fonction pour afficher les bénéfices 
     * @Route("/admin/management/input", name="app_input")
     */
    public function showInput(ManagerRegistry $doctrine)
    {
        $inputs = $doctrine->getRepository(Input::class)->findAll();
        return $this->render('management/input.hmtl.twig', [
            'inputs' => $inputs,
        ]);
    }

    /**
     * fonction pour afficher les blogs
     * @Route("/management/blog", name="show_blog")
     */
    public function showBlog(ManagerRegistry $doctrine):Response
    {
        $blogs = $doctrine->getRepository(Blog::class)->findBy([] , ["publicationDate" => "ASC"]);
        return $this->render('blog/index.html.twig', [
            'blogs' => $blogs,
        ]);
    }

    /**
     * fonction pour afficher les réservation de tous les clients
     * @Route("/admin/management/reservation-session", name="app_gestion_reservation")
     */
    public function showReservationManagement(ManagerRegistry $doctrine):Response
    {

        $reservations = $doctrine->getRepository(Reservation::class)->findAll();
        $sessions = $doctrine->getRepository(Session::class)->findBy([], ['startTime' => "DESC"]);
        return $this->render('management/showReservationSession.html.twig', [
            'reservations' => $reservations,
            'sessions' => $sessions,
        ]);
    }


      /**
     * fonction pour ajouter et/ou modifier un blog
     * @Route("/admin/management/blog/{id_user}/add", name="add_blog")
     * @Route("/admin/management/blog/{id_user}/edit/{id}" , name="edit_blog" )
     * @ParamConverter("blog", options={"id" = "id"})
     * @ParamConverter("user", options={"id" = "id_user"})
     */
    public function addBlog(ManagerRegistry $doctrine , Blog $blog= null ,User $user =null, Request $request):Response
    {
   
        if(!$blog){
            $blog =new Blog();
        }
        // crée le formulaire de type Blog 
        $form = $this->createForm(BlogType::class , $blog );
        $form->handleRequest($request);
        // si envoye et sanitise avec les filter etc protection faille xss puis on execute le tout 
        if($form->isSubmitted() && $form->isValid())
        {
            $imgFile = $form->get('image')->getData();
            if ($imgFile) {
                $newFilename = 'img/imported/'.uniqid().'.'.$imgFile->guessExtension();
                try {
                    $imgFile->move(
                        $this->getParameter('img_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $blog->setImage($newFilename);
            }
            $blog = $form->getData();
            $blog->setUser($user);         
            $entityManager = $doctrine->getManager();
            // hydrate et protection faille sql 
            $entityManager->persist($blog);
            $entityManager->flush();
            $this->addFlash("success" , $blog->getTitle()." à été ajouté/Modifié avec succès");
            return $this->redirectToRoute('show_blog'); 
        }
        return $this->render('management/addBlog.html.twig', [
            'formAddBlog' =>  $form->createView(),
            'edit' => $blog->getId(),
        ]);
    }

    /**
     * fonction pour ajouter et/ou modifier une catégorie
     * @Route("/admin/management/category/add", name="add_category")
     * @Route("/admin/management/category/edit/{id}" , name="edit_category" )
     */
    public function addCategory(ManagerRegistry $doctrine,Category $category = null, Request $request): Response
    {
        // si le film existe pas on crée un nouvelle objet sinon on modifie 
        if(!$category){
            $category =new Category();
        }
        // crée le formulaire de type category 
        $form = $this->createForm(CategoryType::class , $category );
        $form->handleRequest($request);
        // si envoye et sanitise avec les filter etc protection faille xss puis on execute le tout 
        if($form->isSubmitted() && $form->isValid())
        {
            $category = $form->getData();           
            $entityManager = $doctrine->getManager();
            // hydrate et protection faille sql 
            $entityManager->persist($category);
            $entityManager->flush();
            $this->addFlash("success" , $category->getCategoryName()." à été ajouté/Modifié avec succès");
            return $this->redirectToRoute('app_management'); 
        }
        return $this->render('management/addCategory.html.twig', [
            'formAddCategory' =>  $form->createView(),
            'edit' => $category->getId(),
        ]);
    }


    /**
     * function pour ajouter une préstation et l'ajouter à une catégorie précise par son id
     * @Route("/admin/management/addBenefit/{id}", name="add_benefit")
     */
    public function addBenefit(Category $category , ManagerRegistry $doctrine, Benefit $benefit = null, Request $request): Response
    {
        $benefit =new Benefit();
        $form = $this->createForm(BenefitType::class,$benefit);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            // gestionn de l'image de la préstation en elle meme
            $imgFile = $form->get('img')->getData();
            if ($imgFile)
            {
                $newFilename = 'img/imported/'.uniqid().'.'.$imgFile->guessExtension();
                try {
                    $imgFile->move(
                        $this->getParameter('img_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $benefit->setImg($newFilename);
            }
             // on récuperes les images transmises pour la gallerie d'image de la préstation
            $imgMultiple = $form->get('imgCollectionBenefits')->getData();
            // on boucle sur les images
            foreach ( $imgMultiple as $image) 
            {
                // on génére un nouveau nom de fichier
                $fichier = 'img/imported/'.uniqid().'.'.$image->guessExtension();
                // on copie le fichier dans le fichier upload
                $image->move(
                    $this->getParameter('img_directory'),
                    $fichier
                );
                // on stocke l'image dans la BDD (son nom)
                $img = new ImgCollectionBenefit();
                $img->setImg($fichier);
                $benefit->addImgCollectionBenefit($img);
                
            }
            $benefit = $form->getData();
            $category->addBenefit($benefit);
            $entityManager = $doctrine->getManager();
            $entityManager->persist($benefit);
            $entityManager->flush();

            $this->addFlash("success" , $benefit->getTitle()." à été ajouté/Modifié avec succès");
            return $this->redirectToRoute('detail_category' , ['id' => $benefit->getCategory()->getId()]); 
        }
        return $this->render('management/addBenefit.html.twig', [
            'form' =>  $form->createView(),
            'sessionId' => $benefit->getId(),
        ]);
    }

    /**
     * function pour modifié une préstation 
     * @Route("/admin/management/edit/{id}/{benefit_id}" , name="edit_benefit" )
     * @ParamConverter("category", options={"id" = "id"})
     * @ParamConverter("benefit", options={"id" = "benefit_id"})
     */
    public function editBenefit(Category $category , ManagerRegistry $doctrine, Benefit $benefit = null, Request $request): Response
    {
    $form = $this->createForm(BenefitType::class,$benefit);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            // gestionn de l'image de la préstation en elle meme
            $imgFile = $form->get('img')->getData();
            if ($imgFile)
            {
                $newFilename = 'img/imported/'.uniqid().'.'.$imgFile->guessExtension();
                try {
                    $imgFile->move(
                        $this->getParameter('img_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $benefit->setImg($newFilename);
            }
             // on récuperes les images transmises pour la gallerie d'image de la préstation

templates/management/addBenefit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une préstation
{% endblock %}

{% block body %}
	{{ form_start(form) }}
	{{ form_errors(form) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(form.title, { 'label': 'Titre' }) }}
			</div>
			<div class="col-4 mb-4">
				{{ form_row(form.price, { 'label': 'Prix' }) }}
			</div>
			<div class="col-12 mb-4 mt-4">
				{{ form_row(form.description) }}
			</div>
			<div class="col-4">
				{{ form_row(form.img) }}
			</div>
			<hr>
			<h2>Ajout de photos pour la gallerie d'image
			</h2>
			<div class="col-8">
				{{ form_row(form.imgCollectionBenefits) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(form.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/management/addBlog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un blog
{% endblock %}

{% block body %}
	{{ form_start(formAddBlog) }}
	{{ form_errors(formAddBlog) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddBlog.title, { 'label': 'Titre' }) }}
			</div>
			<div class="col-12 mb-4 mt-4">
				{{ form_row(formAddBlog.contents) }}
			</div>
			<div class="row">
				<h3>choisisez si vous voulez poster une vidéo ou si vous voulez poster une image
				</h3>
				<div class="col-4 mb-4">
					{{ form_row(formAddBlog.image) }}
				</div>
				<div class="col-4">
					{{ form_row(formAddBlog.urlVideo, { 'label': "placer l'url de la vidéo ou le liens internet" }) }}
				</div>
				<div class="col-4">
					{{ form_row(formAddBlog.altImage, { 'label': "placer la description de l'image 100 caractères maximum" }) }}
				</div>
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddBlog.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddBlog) }}
{% endblock %}

templates/management/addCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une préstation
{% endblock %}

{% block body %}
	{{ form_start(formAddCategory) }}
	{{ form_errors(formAddCategory) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddCategory.categoryName, { 'label': 'Nom de la catégorie' }) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddCategory.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddCategory) }}
{% endblock %}

templates/management/addInput.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un bénéfices à la liste
{% endblock %}

{% block body %}
	{{ form_start(formAddInput) }}
	{{ form_errors(formAddInput) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddInput.description) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddInput.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddInput) }}
{% endblock %}

templates/management/addReply.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un commentaire!
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="container-message">
					{% if post.user.img %}
						<figure class="avatar">
							<img src="/{{ post.user.img }}" class="img-fluid rounded-start" alt="...">
						</figure>
					{% else %}
						<figure class="avatar">
							<img src="{{asset('img/avatar.jpg')}}" class="img " alt="Avatar">
						</figure>
					{% endif %}
					{% if post.user.id == null %}
						<h5>Compte supprimé</h5>
					{% else %}
						<h5>
							Écrit par :{{post.user.pseudo }}</h5>
					{% endif %}
					<hr class="pink">
					<p>{{ post.contents}}</p>
					<span class="time-left">Posté le :
						{{ post.creationDate | date('d/m/Y H:i')}}</span>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col">
				{{ form_start(formAddReply) }}
				{{ form_errors(formAddReply) }}
				<div class="container">
					<div class="row">
						<div class="col-12 mb-4 mt-4">
							{{ form_row(formAddReply.content, { 'label': 'Répondre au commentaire' }) }}
						</div>
						<div class="row">
							<div class="col-4 mt-4">
								{{ form_row(formAddReply.submit, { 'label': 'Envoyer' }) }}
							</div>
						</div>
					</div>
				</div>
				{{ form_end(formAddReply) }}
			</div>
		</div>
	</div>
{% endblock %}

templates/management/detailBenefit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les préstation par catégorie
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row">
			<h1 class="text-center">
				Ajout des bénéfices pour :
				{{ benefit }}</h1>
		</div>
		<div class="row row-cols-lg-2">
			<div class="col">
				<h2 class="mt-5 mb-5">Les bénéfice liées
				</h2>
				<table id="table_id2" class="table table-striped mt-4 display">
					<thead>
						<tr class="bg-secondary">
							<th scope="col ">Déscription</th>
							<th scope="col ">Désinscrire</th>
						</tr>
					</thead>
					<tbody>
						{% for input in benefit.inputs %}
							<tr>
								<td>{{input}}</td>
								<td>
									<button type="button" class="btn btn-lg bg-secondary mt-2 ">
										<a href="{{ path('remove_input_benefit' , {'benefit_id': benefit.id , 'input_id': input.id }) }}">Désinscrire</a>
									</button>
								{% endfor %}
							</tr>
						</tbody>
					</tbody>
				</table>
			</div>
			<div class="col">
				<h2 class="mt-5 mb-5">Les bénféfices non inscrits
				</h2>
				<table id="table_id3" class="table table-striped mt-4 display">
					<thead>
						<tr class="bg-secondary">
							<th scope="col ">Déscription</th>
							<th scope="col ">Désinscrire</th>
						</tr>
					</thead>
					<tbody>
						{% for input in noBenefits %}
							<tr>
								<td>{{input}}</td>
								<td>
									<button type="button" class="btn btn-lg bg-secondary mt-2 ">
										<a href="{{ path('add_input_benefit' , {'benefit_id': benefit.id , 'input_id': input.id }) }}">Inscrire</a>
									</button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<button type="button" class="btn btn-lg bg-secondary mt-2 ">
				<a href="{{ path('detail_benefit', {'id': benefit.id }) }}">détail préstation</a>
			</button>
		</div>
	</div>
{% endblock %}

templates/management/detailCategory.hmtl.twig
{% extends 'base.html.twig' %}

{% block title %}Les préstation par catégorie{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="text-center"> {{ category }}</h1>
        <button type="button" class="btn btn-lg bg-secondary mt-5  mb-5 col-3 "><a href="{{ path('add_benefit', {'id': category.id}) }}">Ajouter une préstation pour cet catégorie</a></button>
        <table id="table_id" class="table table-striped mt-4 display">
            <thead>
            <tr class="bg-secondary">
                <th scope="col ">Préstation</th>
                <th scope="col">Editer</th>
                <th scope="col">supprimer</th>
            </tr>
            </thead>
            <tbody>
                {% for benefit in category.benefits %}
                <tr>
                    <td><a href="{{ path('detail_edit_benefit', {'id': benefit.id }) }}">{{ benefit }}</a></td>
                    <td><button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('edit_benefit', {'id': category.id , 'benefit_id': benefit.id }) }}">Editer</a></button></td>
                    <td>
                        <button type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-toggle="modal" data-bs-target="#exampleModal{{benefit.id}}">supprimer</i></button>                 
                        <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{benefit.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Confirmer vous la supréssion de : <br>{{benefit}} ? </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                la suppression est définitif êtes vous certain de votre déscicions ? 
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-dismiss="modal" > X annuler</button>
                                <button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('delete_benefit', {'id': benefit.id }) }}">supprimer</a></button>
                            </div>
                        </div>
                    </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('app_management') }}">retour</a></button>
    </div>    
</div>
{% endblock %}

templates/management/showReservationSession.html.twig
{% extends 'base.html.twig' %}
{% block title %}Réservation{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <h1 class="mt-5 mb-5">Listes de toute les sessions en cours et passer </h1>            
                {# {% include "session/_showSession.html.twig" %} #}
                <table id="table_id" class="table table-striped mt-4 display">
                    <thead>
                        <tr class="bg-secondary">
                            <th scope="col ">Id</th>
                            <th scope="col">Préstation</th>
                            <th scope="col">Date déroulement</th>
                            <th scope="col">Nombre de place maximum</th>               
                            <th scope="col">nombre de place réserver</th>
                            <th scope="col">nombre de place restante</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for session in sessions %}   
                        <tr>
                            <td><strong>{{ session.id }} </strong></td>
                            <td><strong>{{ session.benefit}}</strong></td>
                            <td>Le {{ session.startTime | date("d/m/Y")  }}  de {{ session.startTime | date("h:m")  }} à {{ session.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{session.nbPlaceMax}} place(s)</td>
                            <td>Place reserver : {{session.nbPlaceReserved}} place(s)</td>
                            <td>Place restante : {{session.remainingPlaces}} place(s)</td>
                        </tr>             
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <h1 class="mt-5 mb-5">Listes de toutes les réservations</h1>            
            <table id="table_id2" class="table table-striped mt-4 display">
                <thead>
                <tr class="bg-secondary">
                    <th scope="col ">Id Session</th>
                    <th scope="col ">Nom client</th>
                    <th scope="col">Email</th>
                    <th scope="col">N°Tél</th>
                    <th scope="col">Session</th>
                    <th scope="col">date</th>
                    <th scope="col">nombre de place réserver</th>
                    <th scope="col">nombre de place restante</th>
                </tr>
                </thead>
                <tbody>
                {% for reservation in reservations %}   
                    <tr>
                        {% if reservation.session != null %}
                            <td><strong>{{ reservation.session.id }}</strong></td>
                            <td><strong>{{ reservation.name }} {{ reservation.firstName }}</strong></td>
                            <td><strong>{{ reservation.user.email }} </strong></td>
                            <td><strong>{{ reservation.telephone }} </strong></td>
                            <td><strong>{{ reservation.session.benefit}}:</strong></td>
                            <td>Le {{ reservation.session.startTime | date("d/m/Y")  }}  de {{ reservation.session.startTime | date("h:m")  }} à {{ reservation.session.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{reservation.nbPlace}} place(s)</td>
                            <td>Place restante : {{reservation.session.remainingPlaces}} place(s) /  {{reservation.session.nbPlaceMax}}</td> 
                        {% elseif reservation.stage != null %}
                            <td><strong>{{ reservation.stage.id }}</strong></td>
                            <td><strong>{{ reservation.name }} {{ reservation.firstName }}</strong></td>
                            <td><strong>{{ reservation.user.email }} </strong></td>
                            <td><strong>{{ reservation.telephone }} </strong></td>
                            <td><strong>{{ reservation.stage.title}}:</strong></td>
                            <td>Le {{ reservation.stage.startTime | date("d/m/Y")  }}  de {{ reservation.stage.startTime | date("h:m")  }} à {{ reservation.stage.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{reservation.nbPlace}} place(s)</td>
                            <td>Place restante : {{reservation.stage.remainingPlaces}} place(s) /  {{reservation.stage.nbPlaceMax}}</td>
                        {% endif %}
                    </tr>             
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock %}

templates/management/showStage.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion stage{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="mt-5 mb-5">Listes de tout les stages en cours et passer </h1>            
                <button type="button" class="btn btn-primary mt-5 mb-5"><a class="dropdown-item" href="{{ path('add_stage')}}">Ajouter un stage</a></button>
                <table id="table_id" class="table table-striped mt-4 display">
                    <thead>
                    <tr class="bg-secondary">
                        <th scope="col ">Id</th>
                        <th scope="col">Stage</th>
                        <th scope="col">Date déroulement</th>
                        <th scope="col">Nombre de place maximum</th>               
                        <th scope="col">nombre de place réserver</th>
                        <th scope="col">nombre de place restante</th>
                        <th scope="col ">Éditer</th>
                        <th scope="col">Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for stage in stages %}   
                        <tr>
                            <td><strong>{{ stage.id }} </strong></td>
                            <td><strong>{{ stage.title}}</strong></td>
                            <td>Le {{ stage.startTime | date("d/m/Y h:m")  }} au {{ stage.endTime | date("d/m/Y h:m")  }}.</td>
                            <td>Place reserver : {{stage.nbPlaceMax}} place(s)</td>
                            <td>Place reserver : {{stage.nbPlaceReserved}} place(s)</td>
                            <td>Place restante : {{stage.remainingPlaces}} place(s)</td>
                            <td><a class="dropdown-item" href="{{ path('edit_stage' , {'id':stage.id }) }}">Éditer</a></td>
                            <td><a class="dropdown-item" href="{{ path('delete_stage' , {'id':stage.id }) }}">Supprimer</a></td>
                        </tr>             
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}